
name: mobilecoin

on:
  pull_request:
    paths:
      - "*"
  push:
    branches: mc-develop

env:
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly-2022-04-29
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          profile: minimal
      - run: sudo apt install cmake
      - run: cargo build --no-default-features --features="no_std_deps,aesni,force_aesni_support,rdrand,custom_threading" --release --target ${{ matrix.target }}
